SCREENMODE_MAIN				= 1
SCREENMODE_ECONOMY_SUPPLY	= 2
SCREENMODE_ECONOMY_DEMAND	= 3
SCREENMODE_TRANSPORT		= 4

SCREENSUBMODE_NONE			= 0
SCREENSUBMODE_CONSTRUCTION	= 1

val = SCREENMODE_MAIN
sub = SCREENSUBMODE_NONE

def select(new_mode: int):
	global val
	val = new_mode