from ui import gestionMode

VC_DARK_TEXT		    = (228, 231, 234)
VC_DARK_BACKGROUND	    = (9, 13, 17)
VC_DARK_BACKGROUND2	= (20, 24, 28)
VC_DARK_BACKGROUND3	= (47, 56, 66)
VC_DARK_PRIMARY		= (29, 74, 128)
VC_DARK_SECONDARY	    = (38, 47, 58)
VC_DARK_ACCENT	        = (27, 119, 230)


VC_LIGHT_TEXT		    = (14, 17, 22)
VC_LIGHT_BACKGROUND	= (228, 235, 241)
VC_LIGHT_BACKGROUND2	= (217, 224, 230)
VC_LIGHT_BACKGROUND3	= (191, 201, 211)
VC_LIGHT_PRIMARY		= (43, 65, 90)
VC_LIGHT_SECONDARY	    = (134, 168, 203)
VC_LIGHT_ACCENT	    = (62, 111, 163)

VC_TEXT		= VC_LIGHT_TEXT		
VC_BACKGROUND	= VC_LIGHT_BACKGROUND	
VC_BACKGROUND2	= VC_LIGHT_BACKGROUND2	
VC_BACKGROUND3	= VC_LIGHT_BACKGROUND3	
VC_PRIMARY		= VC_LIGHT_PRIMARY		
VC_SECONDARY	= VC_LIGHT_SECONDARY	
VC_ACCENT		= VC_LIGHT_ACCENT		



VC_ROUNDING_SMOOTH = 5
VC_ROUNDING_HARD = 10
VC_MENU_BORDER_WIDTH = 5

VC_PADDING = 5

VC_TOP_BAR_HEIGHT = 60
VC_LARGEUR_SIDEMENU = 470


def VC_change_Background(mode):
	global VC_TEXT, VC_BACKGROUND, VC_BACKGROUND2, VC_BACKGROUND3, VC_PRIMARY, VC_SECONDARY, VC_ACCENT		


	if mode == gestionMode.GestionMode_MODE_LIGHT:
		VC_TEXT = VC_LIGHT_TEXT
		VC_BACKGROUND = VC_LIGHT_BACKGROUND
		VC_BACKGROUND2 = VC_LIGHT_BACKGROUND2
		VC_BACKGROUND3 = VC_LIGHT_BACKGROUND3
		VC_PRIMARY = VC_LIGHT_PRIMARY
		VC_SECONDARY = VC_LIGHT_SECONDARY
		VC_ACCENT = VC_LIGHT_ACCENT
		gestionMode.GestionMode_change_mode(gestionMode.GestionMode_MODE_LIGHT)
			
	
	
	else:
		VC_TEXT = VC_DARK_TEXT
		VC_BACKGROUND = VC_DARK_BACKGROUND
		VC_BACKGROUND2 = VC_DARK_BACKGROUND2
		VC_BACKGROUND3 = VC_DARK_BACKGROUND3
		VC_PRIMARY = VC_DARK_PRIMARY
		VC_SECONDARY = VC_DARK_SECONDARY
		VC_ACCENT = VC_DARK_ACCENT
		gestionMode.GestionMode_change_mode(gestionMode.GestionMode_MODE_DARK)

		
		